bootstrap.yml:
    filepath_for_config: 'app/config/bootstrap.yml'
    parameters:
        type: title
        title-name: Parameters
        children:
            ggm.theming.active_theme:
                type: field
                field-type: text
                field-default: ~
                field-name: GGM Theming Active Theme
                empty-string-when-null: true
            ggm.bootstrap.config:
                type: title
                title-name: Bootstrap Config
                children:
                    ggmArticleBundle:
                        type: title
                        title-name: Article Bundle
                        children:
                            enabled:
                                type: field
                                field-type: choice
                                field-name: Enabled
                                field-choices: {1: asd,2:def,3:lol}
                                field-default: 1
                            root:
                                type: field
                                field-type: multi-choice
                                field-default: {fuch_that_shit:de, 1:as}
                                field-choices: {1:as, 2:de}
                                field-name: Root
                            prefix:
                                type: field
                                field-type: text
                                field-default: a
                                field-name: Prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\ArticleBundle\ggmArticleBundle'
                                field-name: Class
                    ggmClassifiedAdBundle:
                        type: title
                        title-name: Classified Ad Bundle
                        children:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Root
                            prefix:
                                type: field
                                field-type: text
                                field-default: cad
                                field-name: Prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\ClassifiedAdBundle\ggmClassifiedAdBundle'
                                field-name: Class
                    ggmJobAdBundle:
                        type: title
                        title-name: Job Ad Bundle
                        children:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Root
                            prefix:
                                type: field
                                field-type: text
                                field-default: jobs
                                field-name: Prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\JobAdBundle\ggmJobAdBundle'
                                field-name: Class
                    ggmNewsAgencyBundle:
                        type: title
                        title-name: News Agency Bundle
                        children:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Root
                            prefix:
                                type: field
                                field-type: text
                                field-default: news-agency
                                field-name: Prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\NewsAgencyBundle\ggmNewsAgencyBundle'
                                field-name: Class
                    ggmEventCalendarBundle:
                        type: title
                        title-name: Event Calendar Bundle
                        children:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Root
                            prefix:
                                type: field
                                field-type: text
                                field-default: event
                                field-name: Prefix
                            class:
                                type: field
                                field-type: text
                                field-default: 'ggm\EventCalendarBundle\ggmEventCalendarBundle'
                                field-name: Class
                    ggmCustomerBundle:
                        type: title
                        title-name: Customer Bundle
                        children:
                            enabled:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Enabled
                            root:
                                type: field
                                field-type: boolean
                                field-default: false
                                field-name: Root
                            prefix:
                                type: field
                                field-type: text
                                field-default:
                                field-name: Prefix
                            class:
                                type: field
                                field-type: text
                                field-default: '$ggm.theming.active_theme$\CustomerBundle\CustomerBundle'
                                field-name: Class
