parameters_yml:
    filepath_for_config: '/paramet'
    parameters:
        type: title
        childs:
            ggm.global.session.config:
                type: title
                childs:
                    memcache:
                        type: title
                        childs:    
                            servers:
                                type: array
                                array-type: collection
                                array-keys: false
                                array-childs:
                                    type: array
                                    array-type: collection
                                    array-keys: false
                                    array-childs:
                                        fqdn:
                                            type: field
                                            field-type: text
                                            field-default: 'www.example.com'
                                            field-name: 'Adresse'
                                        port:
                                            type: field
                                            field-type: text
                                            field-default: 'www.example.com'
                                            field-name: 'Adresse'
                            options:
                                type: title
                                childs:
                                    prefix:
                                        type: field
                                        field-type: text
                                        field-default: CHANGEME
                                        field-name: 'prefix'
                                    expiretime:
                                        type: field
                                        field-type: text
                                        field-default: 1440
                                        field-name: 'expiretime'
            ggm.global.root_route: 
                type: field
                field-type: text
                field-default: null
                field-name: 'root route'
            ggm.global.phone_country_codes:
                type: titel
                childs:
                    DE:
                        type: field
                        field-type: text
                        field-default: '+49'
                        field-name: 'phone country code'
            ggm.global.email:
                type: titel
                childs:
                    address:
                    type: field
                    field-type: text
                    field-default: webmaster@example.com
                    field-name: 'address'
                sender_name: 
                    type: field
                    field-type: text
                    field-default: webmaster
                    field-name: 'sender name'
