parameters.yml:
    filepath_for_config: 'app/config/parameters.yml'
    parameters:
        type: title 
        title-name: 'parameters'
        childs:
            key:
                type: field
                field-type: multiChoice
                field-default: ~
                field-name: 'choicetype test'
                field-choices: {eintest: local, eintest2: unlocal}
                null-when-empty: true       
            service_fees:
                type: title 
                title-name: 'service_fees'
                childs:
                    regular:
                        type: array 
                        array-name: 'regular'                        
                        array-type: keyValue
                        childs:
                            key:
                                type: field
                                field-type: text
                                field-default: ~
                                field-name: 'FQDN von Service'
                            value:
                                type: title
                                title-name: 'Config für Service'
                                childs:
                                    base_fee:
                                        type: field
                                        field-type: text
                                        field-default: ~
                                        field-name: 'base_fee'
                                    options:
                                        type: title
                                        title-name: 'options'
                                        childs:
                                            item_count_modifier:
                                                type: title
                                                title-name: 'item_count_modifier'
                                                optional: true
                                                childs:
                                                    default_multiplicator:
                                                        type: field
                                                        field-type: text
                                                        field-default: 0.25
                                                        field-name: 'default_multiplicator'
                                                    segments:
                                                            type: array 
                                                            array-name: 'default name'
                                                            array-type: keyValue
                                                            childs:
                                                                key:
                                                                    type: field
                                                                    field-type: text
                                                                    field-default: ~
                                                                    field-name: 'Anzahl Elemente'
                                                                value:
                                                                    type: field
                                                                    field-type: text
                                                                    field-default: ~
                                                                    field-name: 'Multiplikator'

                    commercial:
                        type: array 
                        array-name: 'oben'                        
                        array-type: collection
                        null-when-empty: true
                        childs:
                            0:
                                type: field
                                field-type: text
                                field-default: ~
                                field-name: commercial
                            1:
                                type: field
                                field-type: integer
                                field-default: 1
                                field-name: test
                            segments:
                                type: array 
                                array-name: 'nicht so tief'
                                array-type: keyValue
                                childs:
                                    key:
                                        type: field
                                        field-type: text
                                        field-default: ~
                                        field-name: 'Anzahl Elemente tief'
                                    value:
                                        type: array 
                                        array-name: 'array tief'                        
                                        array-type: collection
                                        null-when-empty: true
                                        childs:
                                            0:
                                                type: field
                                                field-type: text
                                                optional: true
                                                field-default: ~
                                                field-name: tief tiefer optional
                                            1:
                                                type: field
                                                field-type: text
                                                field-default: ~
                                                field-name: tief tiefer nicht optional
