parameters.yml:
    filepath_for_config: 'app/config/parameters.yml'
    parameters:
        type: title 
        title-name: 'default Name'
        childs:
            key:
                type: field
                field-type: multiChoice
                field-default: ~
                field-name: 'choicetype test'
                field-choices: {eintest: local, eintest2: unlocal }       
            service_fees:
                type: title 
                title-name: 'default Name'
                childs:
                    regular:
                        type: array 
                        array-name: 'default name'                        
                        array-type: keyValue
                        array-max: 5
                        childs:
                            key:
                                type: field
                                field-type: text
                                field-default: ~
                                field-name: 'FQDN von Service'
                            value:
                                type: title
                                title-name: 'Config für Service'
                                childs:
                                    base_fee:
                                        type: field
                                        field-type: text
                                        field-default: ~
                                        field-name: 'base_fee'
                                    options:
                                        type: title
                                        title-name: 'options'
                                        childs:
                                            item_count_modifier:
                                                type: title
                                                title-name: 'item_count_modifier'
                                                childs:
                                                    default_multiplicator:
                                                        type: field
                                                        field-type: text
                                                        field-default: 0.25
                                                        field-name: 'default_multiplicator'
                                                    segments:
                                                            type: array 
                                                            array-name: 'default name'
                                                            array-type: keyValue
                                                            array-max: 5
                                                            childs:
                                                                key:
                                                                    type: field
                                                                    field-type: text
                                                                    field-default: ~
                                                                    field-name: 'Anzahl Elemente'
                                                                value:
                                                                    type: field
                                                                    field-type: text
                                                                    field-default: ~
                                                                    field-name: 'Multiplikator'

                    commercial:
                        type: array 
                        array-name: 'default name'                        
                        array-type: collection
                        array-max: 5
                        array-merge: true
                        childs:
                            0:
                                type: field
                                field-type: text
                                field-default: ~
                                field-name: commercial
