parameters.yml:
    filepath_for_config: 'app/config/parameters.yml'
    parameters:
        type: title
        title-name: Parameters
        childs:
            search_connections:
                            type: array
                            array-type: collection
                            array-name: Search Connections
                            childs:
                                0:
                                    type: array
                                    array-type: keyValue
                                    array-name: Search Connection
                                    childs:
                                        key:
                                            type: field
                                            field-type: text
                                            field-name: Connection Type
                                            field-default: 'url'
                                        value:
                                            type: field
                                            field-type: text
                                            field-name: Url
                                            field-default: 'http://10.64.202.98:9200'
