parameters.yml:
    filepath_for_config: "ein pfad ein pfad den jeder mal geht"
    commercial:
        type: array
        array-type: key-value
        array-name: Commercial
        children:
            key:
                type: field
                field-type: text
                field-name: Full Namespace Path
                field-default: null
            value:
                type: title
                title-name: Namespace Configuration
                children:
                    base_fee:
                        type: field
                        field-type: integer
                        field-name: Base Fee
                        field-default: 0
                    options:
                        type: title
                        title-name: Options
                        children:
                            item_count_modifier:
                                type: title
                                title-name: Item Count Modifier
                                optional: true
                                children:
                                    default_multiplicator:
                                        type: field
                                        field-type: number
                                        field-name: Default Multiplicator
                                        field-default: 0.5
                                        field-constraints:
                                            -
                                                constraint-name: range
                                                constraint-options: 
                                                    min: 20
                                                    max: 4000
                                    segments:
                                        type: array
                                        array-type: key-value
                                        array-name: Segments
                                        children:
                                            key:
                                                type: field
                                                field-type: integer
                                                field-name: Anzahl Elemente
                                                field-default: 0
                                            value:
                                                type: field
                                                field-type: number
                                                field-name: Multiplikator
                                                field-default: 0.5
                        
